#!/usr/bin/env ruby

require File.expand_path('../../config/application',  __FILE__)

MHConfig.parse(File.read(ARGV[0]))

MHConfig.hosts.each do |host_name, host|
  host.services.each do |service_name|
    service = MHConfig.services[service_name]
    raise "Unknown service #{service} on host #{host_name}" unless service
    
    check = ServiceCheckJob.new(:service => service, :host => host) 
    check.perform
  end
end